import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeContext } from "./providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr-FR" suppressHydrationWarning>
      <body className="${inter.className} bg-slate-50 dark:bg-slate-950">
        <ThemeContext>
          {children}
        </ThemeContext>
      </body>
    </html>
  );
}
